services:
  gofer-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gofer-bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
